apiVersion: v1
stringData:
  accesskey: xHAcEUiSJYcOqD9zOQSzYE4I3QirjlWVc1mF2vjdCYh
  secretkey: yko-e81fNMPaZdgy73AWo-D7ht6lOcz9I0Rh6dqQksR
  host: 10.1.1.100:3000
  bucket: OneHelios
  location: US
  retention: "7"
  appliance-name: "onehelios"
  smtp-server: "smtp.mydomain.net"
  smtp-port: "25"
  smtp-user: ""
  smtp-password: ""
  smtp-starttls: "false"
  smtp-from: "from@cohesity.com"
  smtp-to: "to@cohesity.com"
kind: Secret
metadata:
  creationTimestamp: null
  name: backup-config
